name: vendorvibe
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter 
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.0.15
  flutter_foreground_task: ^8.17.0
  google_sign_in: ^6.2.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
   android: true
   ios: true
   image_path: "asset/images/icon for vv.png"
  
flutter:

  
  uses-material-design: true


  assets:
    - asset/images/
     


 
